version: "3.8"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/var/lib/mongodb/data"
  api:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: rails s -b 0.0.0.0
    depends_on:
      - db
volumes:
  mongodb:
