version: "3.8"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/var/lib/mongodb/data"
  redis:
    image: "redis:5-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/app"
      - "/app/tmp"
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on:
      - db
      - redis
  api:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: rails s -b 0.0.0.0
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on:
      - db
volumes:
  mongodb:
  redis:
