development:
  clients:
    default:
      database: finlex_development
      hosts:
        - db:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: finlex_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
